### ISSUE TITLE
Dates can be nil is _document_match partial

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#161]
```
ActionView::Template::Error (undefined method `to_formatted_s' for nil:NilClass):
     8: <tr id="<%= name.downcase.parameterize %>-match">
     9:   <td> <%= match ? svg_icon(:found) : svg_icon(:missing) %> </td>
    10:   <td> <%= name %> </td>
    11:   <td> <%= date.to_formatted_s(:short_date) %> </td>
    12:   <td> <%= match ? date.to_formatted_s(:short_date) : "No Matching Document" %> </td>
    13: </tr>
  app/views/certifications/_document_match.html.erb:11:in `_app_views_certifications__document_match_html_erb___670760745404812357_70338711879480'
  app/views/certifications/mismatched_documents.html.erb:50:in `_app_views_certifications_mismatched_documents_html_erb___1198966621371306021_70338711980800'
  /app/caseflow/.rbenv/versions/2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  app/controllers/certifications_controller.rb:22:in `new'
```

**Comment by shanear** [comment]
closed by:
https://github.com/department-of-veterans-affairs/caseflow-certification/pull/176
