### ISSUE TITLE
RecordNotFound is logged with level FATAL, should be logged with a lower level

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-certification#168]
```
F, [2016-03-10T15:36:11.272785 #43150] FATAL -- : [*******@va.gov (RO13)]
ActiveRecord::RecordNotFound (Couldn't find Records::Case with 'bfkey'=123C):
  app/services/appeal_repository.rb:22:in `block in find'
  app/services/metrics_service.rb:8:in `block in timer'
  /app/caseflow/.rbenv/versions/2.2.4/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
  app/services/metrics_service.rb:7:in `timer'
  app/services/appeal_repository.rb:21:in `find'
  app/models/appeal.rb:99:in `find'
  app/controllers/certifications_controller.rb:72:in `appeal'
  app/controllers/certifications_controller.rb:62:in `verify_access'
```

**Comment by orischwartz** [comment]
Marking as wontfix for now, users shouldn't be landing on appeal pages that 404 so we want to track these
